matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: scSOsO4ftYIzUVoub0poQaVUSTingOaC8x0aruonFYx0DsqucZBXooCMHLRdrXG6SU9Zf18oZHtbYO61DhuB5atCmjYpeiTL7xojB/iImJnfnyfRGlGFjvYdQma195FIqvmF/s7s8eeZ41DUFqXZFnDHRp/3bRVpWKp0TFNBqiBQcxgvbyKDyNkWD45gwo+wcZni5lZdF+oLGT4uWAaJDL18AjGzuQ2rlaXEWIqXv+KyFXjxXk5TTc+ymuc8kXb5i6Z4D768Tsr/CXY7CIvBkBivAJ5kddUvC48sWP+RtorI72nmOYm/G/LM0RWUlZ9vpHx8NVd9lDW3Yh/nd+QKdI+2u9IFSVnnSnZBLOfr0Fh79i+OmpYPImjPvczj30ujyLHvX+ktn9B/HaSsPbzpL2BZn3uH4t5iohwl3QSJf3i1/NCpwdWlJfOwmRwVHBA7/wcvp9Eeinvoc/i+uekjFrhmyVOgPa4nCKQG44R9Tsnz9G2spsLgLMXSA9j6h/xqijfZ0rKMnhW2ypzJZkbGYpLDx5yfOxEcqCwBygxws/hc4qsSwkXKePbHeH253gwrV7vqiROwc+T3SFZJROdlRwg9+k/0/+UWX/YwZeAjqec5i38VXg2G19Iq6l+OO/uyRATj1JN1Tq035UpV/UsoyateTMMdsWaOYUyWfJNhnL4=
