name: Generate a TEST Release

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+rc[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  set-release-version:
    name: Set Release Version
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.set-release-version.outputs.release-version }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          fetch-depth: 0

      - name: Set the release version
        id: set-release-version
        run: echo "release-version=${GITHUB_REF#refs/*/}" >> "${GITHUB_OUTPUT}"

  create-release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - set-release-version

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: Bullrich/generate-release-changelog@6b60f004b4bf12ff271603dc32dbd261965ad2f2  # v2.0.2
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191  # v2.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ needs.set-release-version.outputs.release-version }}
          body: ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: true
